	integer Prob_choice,prints
	integer Prob_matter
	integer theta_23_control
	integer theta_13_control
	real nu_control
	integer ch_control,k2k_control
	integer mino_control,sk_control
	integer XS_control
	integer control_180,UP_control
	integer MR_control, PC_control
	integer neu_control,neubar_control
	integer neuneubar_control,binA,binB
	integer control_180_test
	integer hierarchy
	integer unphysical

	COMMON /GLOB/ Prob_choice,prints
	COMMON /GLOB/ Prob_matter
	COMMON /GLOB/ theta_23_control
	COMMON /GLOB/ theta_13_control
	COMMON /GLOB/ nu_control
	COMMON /GLOB/ ch_control,k2k_control
	COMMON /GLOB/ mino_control,sk_control
	COMMON /GLOB/ XS_control
	COMMON /GLOB/ control_180,UP_control
	COMMON /GLOB/ MR_control, PC_control
	COMMON /GLOB/ neu_control,neubar_control 
	COMMON /GLOB/ neuneubar_control,binA,binB
	COMMON /GLOB/ control_180_test
	COMMON /GLOB/ hierarchy
	COMMON /GLOB/ unphysical



















