         real*8  MinData20,MinNuMu_AtmCV,MinNuMu_AtmNFid,
     c  MinNuMuBarAtmCV,MinNuMuBarAtmNFid,MinNuMuBarDomBeamCV,
     c  MinNuMuBarEnhaBeam,MinNuMuDomBeam,MinNuMuDomBeamNFid
       
        common/MINOS_20/ MinData20(8,2,40),MinNuMu_AtmCV(7,2,25),
     c MinNuMu_AtmNFid(7,2,25),MinNuMuBarAtmCV(7,2,25),
     c MinNuMuBarAtmNFid(7,2,25),MinNuMuBarDomBeamCV(7,2,25),
     c MinNuMuBarEnhaBeam(7,2,25),MinNuMuDomBeam(7,2,25),
     c MinNuMuDomBeamNFid(7,2,25)

     
     
